{{- if not .Values.gitscan.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitscan.fullname" . }}
  labels:
{{ include "gitscan.labels" . | indent 4 }}
type: Opaque
data:
  GITHUB_TOKEN: {{ .Values.gitscan.gitHubToken | default "" | b64enc | quote }}
  TRIVY_TOKEN: {{ .Values.gitscan.serverToken | default "" | b64enc | quote }}
{{- if not .Values.gitscan.registryCredentialsExistingSecret }}
  TRIVY_USERNAME: {{ .Values.gitscan.registryUsername | default "" | b64enc | quote }}
  TRIVY_PASSWORD: {{ .Values.gitscan.registryPassword | default "" | b64enc | quote }}
{{- end -}}
{{- end }}
