apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gitscan.fullname" . }}
  labels:
{{ include "gitscan.labels" . | indent 4 }}
{{- if (.Values.gitscan.serviceAccount).annotations }}
  annotations:
{{ toYaml .Values.gitscan.serviceAccount.annotations | indent 4 }}
{{- end }}
  namespace: {{ .Release.Namespace }}